### ISSUE TITLE
如何替换冲突硬件的dsdt源

### ISSUE THREAD

**Issue by zzxxxxxzxxxz** [edk2-porting/edk2-msm8998#27]

**Comment by zzxxxxxzxxxz** [comment]
小米mix2，pep驱动冲突

**Comment by Idonotkno** [comment]
@zzxxxxxzxxxz Try the touch screen, don't waste time, After getting the touch screen, go in and see what happened to usb.

**Comment by Idonotkno** [comment]
@zzxxxxxzxxxz 去看看触屏吧，触屏很容易，进去之后看看usb发生了什么就是了，非要在这里吊死就是浪费时间，如果不要pep，那我建议也别装了

**Comment by zzxxxxxzxxxz** [comment]
触摸驱动需要GPIO和PEP的支持

**Comment by Idonotkno** [comment]
@zzxxxxxzxxxz 你配置一下i2c和触屏设备不就完了，它又不需要usb，mix2的其他基本上是好的。。

**Comment by zzxxxxxzxxxz** [comment]
mix2早就有触屏驱动了

**Comment by zzxxxxxzxxxz** [comment]
ok

**Comment by zzxxxxxzxxxz** [comment]
ok

**Comment by zzxxxxxzxxxz** [comment]
主要是pep打不上

**Comment by Idonotkno** [comment]
@zzxxxxxzxxxz 这边测试pep是好的。。。。。。
。。。。
。。。。不好的是usb，不是pep。。。

**Comment by zzxxxxxzxxxz** [comment]
我试试

**Comment by zzxxxxxzxxxz** [comment]
你用的是哪个触屏驱动，是mix2s上的不。

**Comment by zzxxxxxzxxxz** [comment]
无法使用

**Comment by zzxxxxxzxxxz** [comment]
你用的驱动列表可以报一下不，我这蓝屏了
