### ISSUE TITLE
Compiling and using in different architecture

### ISSUE THREAD

**Issue by TYeniyayla** [edk2-porting/edk2-msm8998#32]
### Prerequisites

* [y ] Have you read the readme?
* [n] Do you (want to) have your device in the supported list?
* [n ] Does the device have a Snapdragon 835 SOC?

### Description
I want to edit for Snapdragon 821 ie MSM8996_B7. I have a Xiaomi Mi5s Plus phone, it doesn't have 2 slots and I want to use this project on it. What path should I follow?

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by qaz6750** [comment]
Sorry, Qualcomm 821 cannot be used, and there is no supported uefi on Android phones

**Comment by qaz6750** [comment]
At the same time, 821 can only start the UEFI of arm32, but this is useless

And Qualcomm 821 should not be mentioned here. Thank you for your question

**Comment by ghost** [comment]
Snapdragon 821 doesn't have all the necessary uefi, linux and windows qualcomm drivers to create a edk2 port. And also its bootloader is arm32, so you can only use 32-bit OSes without some hacks.

**Comment by binarymaster** [comment]
> so you can only use 32-bit OSes without some hacks

Boot Shim probably could help: https://github.com/imbushuo/boot-shim

**Comment by TYeniyayla** [comment]
Thanks for all the answers. I honestly didn't know that much before I asked. I thought that since I had compiled kernel and linux based operating systems before, it has a similar logic. It has a very different logic. Thanks again for the information.
