### ISSUE TITLE
BSOD IPI_WATCHDOG_TIMEOUT Windows PE LG V30+

### ISSUE THREAD

**Issue by SwedMlite** [edk2-porting/edk2-msm8998#35]
### Prerequisites

* [ V ] Have you read the readme?
* [ V ] Do you (want to) have your device in the supported list?
* [ V ] Does the device have a Snapdragon 835 SOC?

### Description
BSOD IPI_WATCHDOG_TIMEOUT Windows PE
My device is LG V30+ US998 128GB.
First it loads, 
![photo_2023-02-16_07-36-50 (2)](https://user-images.githubusercontent.com/111647816/219355000-96a5150d-6de5-4569-9458-8ca250e77012.jpg)

then the dots stop moving, hangs for a long time and 
then a BSOD appears.
![IMG_20230215_222456](https://user-images.githubusercontent.com/111647816/219355024-66faaec8-dff9-4d70-b837-849e1d2d4bfb.jpg)

[Description of the bug or feature]

**Expected behavior:** [What you expected to happen]
Working WinPE

**Actual behavior:** [What actually happened]
BSOD Windows PE

**Comment by SwedMlite** [comment]
Now I tried Windows 11 PE , BSOD DPC_WATCHDOG_VIOLATION

**Comment by qaz6750** [comment]
* You should know that this repository has not been maintained for a long time, and the relevant LG devices have not been migrated to edk2-msm, and the maintenance personnel have not updated the status for a long time
