### ISSUE TITLE
build sagit failed

### ISSUE THREAD

**Issue by HolmesPsherlock** [edk2-porting/edk2-msm8998#36]
### Description

[Description of the bug or feature]
build sagit failed
**Expected behavior:** [What you expected to happen]
bash build.sh --device sagit
**Actual behavior:** [What actually happened]
Active Platform          = /root/edk2-msm8998/MSM8998Pkg/Devices/sagit.dsc
..#..... done!
Building ... /root/edk2-msm8998/edk2/ArmPkg/Library/CompilerIntrinsicsLib/CompilerIntrinsicsLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BaseStackCheckLib/BaseStackCheckLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/UefiDriverEntryPoint/UefiDriverEntryPoint.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/UefiLib/UefiLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ArmPkg/Library/ArmCacheMaintenanceLib/ArmCacheMaintenanceLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BasePeCoffLib/BasePeCoffLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ArmPkg/Library/ArmLib/ArmBaseLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ArmPkg/Library/DebugPeCoffExtraActionLib/DebugPeCoffExtraActionLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/RuntimeDxeReportStatusCodeLib/RuntimeDxeReportStatusCodeLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/UefiDevicePathLib/UefiDevicePathLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/UefiRuntimeLib/UefiRuntimeLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/UefiMemoryAllocationLib/UefiMemoryAllocationLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BasePrintLib/BasePrintLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/UefiBootServicesTableLib/UefiBootServicesTableLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/UefiRuntimeServicesTableLib/UefiRuntimeServicesTableLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/PeiDxeDebugLibReportStatusCode/PeiDxeDebugLibReportStatusCode.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BaseLib/BaseLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/DxePcdLib/DxePcdLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BaseDebugPrintErrorLevelLib/BaseDebugPrintErrorLevelLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/EmbeddedPkg/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BaseCpuLib/BaseCpuLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellNetwork1CommandsLib/UefiShellNetwork1CommandsLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellInstall1CommandsLib/UefiShellInstall1CommandsLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellDebug1CommandsLib/UefiShellDebug1CommandsLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellDriver1CommandsLib/UefiShellDriver1CommandsLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellLevel3CommandsLib/UefiShellLevel3CommandsLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellLevel1CommandsLib/UefiShellLevel1CommandsLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellLevel2CommandsLib/UefiShellLevel2CommandsLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/NetworkPkg/Library/DxeNetLib/DxeNetLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellBcfgCommandLib/UefiShellBcfgCommandLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellCommandLib/UefiShellCommandLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiHandleParsingLib/UefiHandleParsingLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ShellPkg/Library/UefiShellLib/UefiShellLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BaseOrderedCollectionRedBlackTreeLib/BaseOrderedCollectionRedBlackTreeLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/UefiFileHandleLib/UefiFileHandleLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/DxeSecurityManagementLib/DxeSecurityManagementLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/EmbeddedPkg/Library/DxeDtPlatformDtbLoaderLibDefault/DxeDtPlatformDtbLoaderLibDefault.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/DxeCrc32GuidedSectionExtractLib/DxeCrc32GuidedSectionExtractLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ArmPkg/Library/ArmExceptionLib/ArmExceptionLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/DxeExtractGuidedSectionLib/DxeExtractGuidedSectionLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ArmPkg/Library/DefaultExceptionHandlerLib/DefaultExceptionHandlerLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ArmPkg/Library/ArmDisassemblerLib/ArmDisassemblerLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/DxeCoreMemoryAllocationLib/DxeCoreMemoryAllocationLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/DxeCoreHobLib/DxeCoreHobLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/DxeCoreEntryPoint/DxeCoreEntryPoint.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenanceManagerUiLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/BootManagerUiLib/BootManagerUiLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/DeviceManagerUiLib/DeviceManagerUiLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/FileExplorerLib/FileExplorerLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/DxeCapsuleLibFmp/DxeRuntimeCapsuleLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/BaseBmpSupportLib/BaseBmpSupportLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/EmbeddedPkg/Library/TimeBaseLib/TimeBaseLib.inf [AARCH64]
Building ... /root/edk2-msm8998/MSM8998Pkg/Library/VirtualRealTimeClockLib/VirtualRealTimeClockLib.inf [AARCH64]
Building ... /root/edk2-msm8998/MSM8998Pkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/DxeCapsuleLibNull/DxeCapsuleLibNull.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/CustomizedDisplayLib/CustomizedDisplayLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/VariablePolicyLib/VariablePolicyLibRuntimeDxe.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/BaseVariableFlashInfoLib/BaseVariableFlashInfoLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/VarCheckLib/VarCheckLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/AuthVariableLibNull/AuthVariableLibNull.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/TpmMeasurementLibNull/TpmMeasurementLibNull.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BaseSynchronizationLib/BaseSynchronizationLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdePkg/Library/BaseSafeIntLib/BaseSafeIntLib.inf [AARCH64]
Building ... /root/edk2-msm8998/MSM8998Pkg/Library/MemoryInitPeiLib/PeiMemoryAllocationLib.inf [AARCH64]
Building ... /root/edk2-msm8998/MSM8998Pkg/Library/PlatformPeiLib/PlatformPeiLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/ArmPlatformPkg/Library/ArmPlatformStackLib/ArmPlatformStackLib.inf [AARCH64]
Building ... /root/edk2-msm8998/edk2/MdeModulePkg/Library/LzmaCustomDecompressLib/LzmaCustomDecompressLib.inf [AARCH64]
In file included from /root/edk2-msm8998/MSM8998Pkg/Library/MemoryInitPeiLib/MemoryInitPeiLib.c:26:
/root/edk2-msm8998/MSM8998Pkg/Include/Configuration/DeviceMemoryMap.h:47:19: error: ‘ARM_MEMORY_REGION_ATTRIBUTE_NONSECURE_DEVICE’ undeclared here (not in a function); did you mean ‘ARM_MEMORY_REGION_ATTRIBUTE_DEVICE’?
   47 | #define NS_DEVICE ARM_MEMORY_REGION_ATTRIBUTE_NONSECURE_DEVICE
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/edk2-msm8998/MSM8998Pkg/Include/Configuration/DeviceMemoryMap.h:47:19: note: in definition of macro ‘NS_DEVICE’
   47 | #define NS_DEVICE ARM_MEMORY_REGION_ATTRIBUTE_NONSECURE_DEVICE
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [GNUmakefile:300: /root/edk2-msm8998/workspace/Build/MSM8998Pkg/RELEASE_GCC5/AARCH64/MSM8998Pkg/Library/MemoryInitPeiLib/PeiMemoryAllocationLib/OUTPUT/MemoryInitPeiLib.obj] Error 1

build.py...
 : error 7000: Failed to execute command
        make -s tbuild [/root/edk2-msm8998/workspace/Build/MSM8998Pkg/RELEASE_GCC5/AARCH64/MSM8998Pkg/Library/MemoryInitPeiLib/PeiMemoryAllocationLib]

build.py...
 : error F002: Failed to build module
        /root/edk2-msm8998/MSM8998Pkg/Library/MemoryInitPeiLib/PeiMemoryAllocationLib.inf [AARCH64, GCC5, RELEASE]

- Failed -
Build end time: 14:10:04, Apr.26 2023
Build total time: 00:00:09

+ return 1

**Comment by qaz6750** [comment]
Due to upstream EDK2 issues,  build not supported

**Comment by qaz6750** [comment]
* https://github.com/edk2-porting/edk2-msm8998/commit/e28e3fdfa195561162e4474ff8cfc95cd04dc649
The issue has now been fixed
